spring:
  application:
    name: api-service
  config:
    import: optional:configserver:http://localhost:8888
  cloud:
    config:
      discovery:
        enabled: true
        service-id: configserver
      enabled: true
      retry:
        max-attempts: 5

server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    allow-redirects: false
    eureka-server-connect-timeout-seconds: 5
    eureka-server-read-timeout-seconds: 5
    register-with-eureka: true
  instance:
    prefer-ip-address: true
