pipeline{
	agent any

    stages{
		stage("product-server pipeline started info"){
			steps{
				sh '''
					curl --json '{"chat_id": "-1002010516337", "text": "#product\nproduct-service deploy pipeline started" }' \
						 https://api.telegram.org/bot7131840357:AAEIxrvvdTf532WG72PzC3xHsZf0hh6BItQ/sendMessage
                '''
            }
        }
        stage("product-server docker build") {
			steps{
				sh '''
					cd product-service
					docker build -t product .
				'''
            }
        }

        stage("product-server deploy") {
			steps{
				sh '''
					cd product-service
					docker rm -f product-service-container
					docker run --name "product-service-container" --network=host -d product
					curl --json '{"chat_id": "-1002010516337", "text": "#product\nproduct-service deploy pipeline finished" }' \
						 https://api.telegram.org/bot7131840357:AAEIxrvvdTf532WG72PzC3xHsZf0hh6BItQ/sendMessage
				'''
            }
        }
    }
    
    post {

		aborted {
			script{
				sh '''
					curl --json '{"chat_id": "-1002010516337", "text": "#product\nproduct-service deploy pipeline aborted" }' \
						 https://api.telegram.org/bot7131840357:AAEIxrvvdTf532WG72PzC3xHsZf0hh6BItQ/sendMessage
				'''
            }
        }

        failure {
			script {
				sh '''
					curl --json '{"chat_id": "-1002010516337", "text": "#product\nproduct-service deploy pipeline failed" }' \
						 https://api.telegram.org/bot7131840357:AAEIxrvvdTf532WG72PzC3xHsZf0hh6BItQ/sendMessage
				'''
			}
		}
    }
}