server:
  port: 8765

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      httpclient:
        connect-timeout: 2500
        response-timeout: 60s
        pool:
          max-idle-time: 2000
      routes:
        - id: api-service
          uri: ld://api-service
          predicates:
            - Path=/api-service/**
      filter:
        strip-prefix:
          enabled: false
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

logging:
  level:
    org.springframework: trace