server:
  port: 8443
#  ssl:
#    enabled: true
#    key-store: classpath:product-keystore.jks
#    key-store-password: password
#    key-password: password

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/product
    username: product
    password: product
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      schema-locations: classpath:sql/schema.sql
      mode: always

  cloud:
    consul:
      retry:
        max-attempts: 5
        enabled: true
      host: soa-consul
      port: 8500
